
include("ComMatrix_test.jl")
include("Constructors_test.jl")
include("Grid_and_points_test.jl")
include("Views_test.jl")
include("Subsetting_test.jl")
include("Dropping_test.jl")
include("Assemblage_tests.jl")
include("GetSet_test.jl")
include("Operations_test.jl")
include("Randomizations_test.jl")
include("Show_test.jl")
include("PlotRecipes_test.jl")
include("Analysis_tests.jl")
include("Nested_views_test.jl")
include("RasterData_test.jl")
