# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 1.1
  - nightly

notifications:
  email: mkborregaard@snm.ku.dk

branches:
  only:
  - master
  - mkb/dev

matrix:
  allow_failures:
    - julia: nightly


# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'import Pkg; Pkg.add(PackageSpec(url = pwd())); Pkg.build("SpatialEcology"); Pkg.test("SpatialEcology"; coverage=true)'

after_success:
- julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
