xmin(g::GridTopology) = g.xmin
ymin(g::GridTopology) = g.ymin
cellsize(g::GridTopology) = g.xcellsize, g.ycellsize
xcellsize(g::GridTopology) = g.xcellsize
ycellsize(g::GridTopology) = g.ycellsize
xcells(g::GridTopology) = g.xcells
ycells(g::GridTopology) = g.ycells
cells(g::GridTopology) = g.xcells, g.ycells
xmax(g::GridTopology) = g.xmin + g.xcellsize*g.xcells
ymax(g::GridTopology) = g.ymin + g.ycellsize*g.ycells
xrange(g::GridTopology) = xmin(g):xcellsize(g):xmax(g)
yrange(g::GridTopology) = ymin(g):ycellsize(g):ymax(g)
boundingbox(g::GridTopology) = Bbox(xmin(g), xmax(g), ymin(g), ymax(g))
show(io::IO, b::Bbox) = println("xmin:\t$(g.xmin)\nxmax:\t$(g.xmax)\nymin:\t$(g.ymin)\nymax:\t$(g.ymax)\n")

xmin(g::AbstractGridData) = xmin(g.grid)
ymin(g::AbstractGridData) = ymin(g.grid)
cellsize(g::AbstractGridData) = cellsize(g.grid)
xcellsize(g::AbstractGridData) = xcellsize(g.grid)
ycellsize(g::AbstractGridData) = ycellsize(g.grid)
xcells(g::AbstractGridData) = xcells(g.grid)
ycells(g::AbstractGridData) = ycells(g.grid)
cells(g::AbstractGridData) = cells(g.grid)
xmax(g::AbstractGridData) = xmax(g.grid)
ymax(g::AbstractGridData) = ymax(g.grid)
xrange(g::AbstractGridData) = xrange(g.grid)
yrange(g::AbstractGridData) = yrange(g.grid)
boundingbox(g::AbstractGridData) = boundingbox(g.grid)
